server:
  port: 8080
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 10s
  application:
    name: template
  profiles:
    active: dev
  messages:
    # 国际化资源文件路径
    basename: i18n/messages
  jackson:
    default-property-inclusion: non_null

  datasource:
    hikari:
      #连接超时时间：毫秒，小于250毫秒，否则被重置为默认值30秒
      connection-timeout: 2000
      #最小空闲连接，默认值10，小于0或大于maximum-pool-size，都会重置为maximum-pool-size
      minimum-idle: 5
      #最大连接数，小于等于0会被重置为默认值10；大于零小于1会被重置为minimum-idle的值
      maximum-pool-size: 20
      #空闲连接最大存活时间，默认值600000（10分钟），大于等于max-lifetime且max-lifetime>0，会被重置为0；不等于0且小于10秒，会被重置为10秒。
      idle-timeout: 200000
      #连接池返回的连接默认自动提交，默认只 true
      auto-commit: true
      # 连接最大存活时间，不等于0且小于30秒，会被重置为默认值30分钟.设置应该比mysql设置的超时时间短
      max-lifetime: 1800000
      #用于测试连接是否可用的查询语句
      connection-test-query: select 1

springdoc:
  swagger-ui:
    operations-sorter: method

decorator:
  datasource:
    p6spy:
      logging: slf4j
      log-format: executionTime:%(executionTime) || %(sql)

#系统密钥
security:
  key: 1~@2pz8K